# Generated by Django 4.2.23 on 2025-07-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foldername", models.CharField(max_length=100)),
                ("flight_field_id", models.CharField(max_length=100)),
                ("poject", models.CharField(max_length=100)),
                (
                    "flight_type",
                    models.CharField(
                        choices=[
                            ("MS", "MS"),
                            ("3D", "3D"),
                            ("Thermal", "Thermal"),
                            ("RGB", "RGB"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "drone_type",
                    models.CharField(
                        choices=[
                            ("M3M-1", "M3M-1"),
                            ("M3M-2", "M3M-2"),
                            ("M4T", "M4T"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drone_pilot",
                    models.CharField(
                        choices=[
                            ("Ivar", "Ivar"),
                            ("Frederic", "Frederic"),
                            ("Christopher", "Christopher"),
                            ("Kristoffer", "Kristoffer"),
                            ("Ludvik", "Ludvik"),
                            ("Jorgen", "Jorgen"),
                            ("Fahad", "Fahad"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reflectance_panel",
                    models.CharField(
                        choices=[("New", "New"), ("Old", "Old"), ("Carpet", "Carpet")],
                        max_length=10,
                    ),
                ),
                ("flight_date", models.DateField()),
                ("flight_start", models.CharField(max_length=10)),
                ("flight_endstart", models.CharField(max_length=10)),
                ("flight_comments", models.CharField(max_length=200)),
                ("p4d_step1", models.CharField(max_length=100)),
                (
                    "p4d_step1_done_by",
                    models.CharField(
                        choices=[
                            ("Ivar", "Ivar"),
                            ("Frederic", "Frederic"),
                            ("Christopher", "Christopher"),
                            ("Kristoffer", "Kristoffer"),
                            ("Ludvik", "Ludvik"),
                            ("Jorgen", "Jorgen"),
                            ("Fahad", "Fahad"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "p4d_step1_workable_data",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=10
                    ),
                ),
                (
                    "p4d_processing",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=10
                    ),
                ),
                (
                    "p4d_processing_done_by",
                    models.CharField(
                        choices=[
                            ("Ivar", "Ivar"),
                            ("Frederic", "Frederic"),
                            ("Christopher", "Christopher"),
                            ("Kristoffer", "Kristoffer"),
                            ("Ludvik", "Ludvik"),
                            ("Jorgen", "Jorgen"),
                            ("Fahad", "Fahad"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("p4d_processing_pc", models.CharField(max_length=100)),
                ("p4d_processing_comments", models.CharField(max_length=200)),
                ("flight_height", models.CharField(max_length=10)),
                ("flight_side_over", models.CharField(max_length=10)),
                ("flight_front_over", models.CharField(max_length=10)),
                ("flight_wind_speed", models.CharField(max_length=10)),
                ("flight_drone_type", models.CharField(max_length=10)),
                ("new_folder_name", models.CharField(max_length=200)),
                ("root_folder", models.CharField(max_length=200)),
                ("flight_path", models.CharField(max_length=200)),
                ("p4d_path", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("scheduled_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("flown", models.BooleanField(default=False)),
                ("frequency_days", models.IntegerField(default=7)),
                (
                    "pilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mainapp.pilot",
                    ),
                ),
            ],
        ),
    ]
