# Generated by Django 4.2.23 on 2025-07-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight_log",
            name="poject",
        ),
        migrations.AddField(
            model_name="flight_log",
            name="project",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="drone_pilot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ivar", "Ivar"),
                    ("Frederic", "Frederic"),
                    ("Christopher", "Christopher"),
                    ("Kristoffer", "Kristoffer"),
                    ("Ludvik", "Ludvik"),
                    ("Jorgen", "Jorgen"),
                    ("Fahad", "Fahad"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="drone_type",
            field=models.CharField(
                blank=True,
                choices=[("M3M-1", "M3M-1"), ("M3M-2", "M3M-2"), ("M4T", "M4T")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_drone_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_endstart",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_field_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_front_over",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_height",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_side_over",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_start",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_wind_speed",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="foldername",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="new_folder_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_processing",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_processing_comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_processing_done_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ivar", "Ivar"),
                    ("Frederic", "Frederic"),
                    ("Christopher", "Christopher"),
                    ("Kristoffer", "Kristoffer"),
                    ("Ludvik", "Ludvik"),
                    ("Jorgen", "Jorgen"),
                    ("Fahad", "Fahad"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_processing_pc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_step1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_step1_done_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ivar", "Ivar"),
                    ("Frederic", "Frederic"),
                    ("Christopher", "Christopher"),
                    ("Kristoffer", "Kristoffer"),
                    ("Ludvik", "Ludvik"),
                    ("Jorgen", "Jorgen"),
                    ("Fahad", "Fahad"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_step1_workable_data",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="reflectance_panel",
            field=models.CharField(
                blank=True,
                choices=[("New", "New"), ("Old", "Old"), ("Carpet", "Carpet")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="root_folder",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
