# Generated by Django 4.2.23 on 2025-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_remove_flight_log_poject_flight_log_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight_log",
            name="flight_date",
            field=models.CharField(max_length=20),
        ),
    ]
