# Generated by Django 4.2.23 on 2025-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_flight_log_flight_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight_log",
            name="flight_date",
            field=models.DateField(),
        ),
    ]
