# Generated by Django 4.2.23 on 2025-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_flight_log_flight_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight_log",
            name="flight_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MS", "MS"),
                    ("3D", "3D"),
                    ("Thermal", "Thermal"),
                    ("RGB", "RGB"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
