# Generated by Django 4.2.23 on 2025-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_flight_log_flight_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(blank=True, max_length=100, null=True)),
                ("short_id", models.CharField(blank=True, max_length=100, null=True)),
                ("long_id", models.CharField(blank=True, max_length=100, null=True)),
                ("crop", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_of_field_plot",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "multispectral",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "three_dimensional",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "thermal",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rgb",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "flying_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "submission_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "project_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "data_delivery_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vollebekk_responsible",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sowing_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "measuring_ground_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
