# Generated by Django 4.2.23 on 2025-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fields",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
