# Generated by Django 4.2.23 on 2025-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_fields_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight_log",
            name="flight_drone_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_endstart",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_front_over",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_height",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_side_over",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_start",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MS", "MS"),
                    ("3D", "3D"),
                    ("Thermal", "Thermal"),
                    ("RGB", "RGB"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="flight_wind_speed",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_processing",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="p4d_step1_workable_data",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight_log",
            name="reflectance_panel",
            field=models.CharField(
                blank=True,
                choices=[("New", "New"), ("Old", "Old"), ("Carpet", "Carpet")],
                max_length=100,
                null=True,
            ),
        ),
    ]
