# Generated by Django 4.2.23 on 2025-07-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_alter_flight_log_flight_drone_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("soil_temperature", models.FloatField(blank=True, null=True)),
                ("soil_moisture", models.FloatField(blank=True, null=True)),
                ("air_temperature", models.FloatField(blank=True, null=True)),
                ("air_humidity", models.FloatField(blank=True, null=True)),
                ("battery", models.FloatField(blank=True, null=True)),
                ("rainfall", models.FloatField(blank=True, null=True)),
                ("crop_type", models.CharField(blank=True, max_length=100)),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="mainapp.sensor",
                    ),
                ),
            ],
            options={
                "unique_together": {("sensor", "timestamp")},
            },
        ),
    ]
